#!/bin/bash
# Simple wrapper to not duplicate .script files. Reads extra args from .stdin
# file, and assumes the actual input file is .c.

if [[ -e ${SRCDIR}/test/${TESTNAME}.stdin ]]; then
	read ARGS
fi
${SRCDIR}/hawkmoth.py ${ARGS} ${SRCDIR}/test/${TESTNAME}.c
