# -*- makefile -*-
# SPDX-FileCopyrightText: 2017 Jani Nikula <jani@nikula.org>
# SPDX-License-Identifier: BSD-2-Clause

test_dir := test

RST := $(RST) $(test_dir)/README.rst

.PHONY: test
test:
	pytest -n auto

.PHONY: test-verbose
test-verbose:
	pytest -n auto -vv

# Ensure a) update-examples works, and b) examples have been updated.
.PHONY: check-examples
check-examples:
	python3 -m $(test_dir).update_examples | diff -u $(doc_dir)/examples.rst -

.PHONY: quick-test
quick-test:
	pytest -n auto -m "not full"

.PHONY: test-coverage
test-coverage:
	pytest -n auto --cov=src/hawkmoth --cov-report=term

.PHONY: test-coverage-html
test-coverage-html:
	pytest -n auto --cov=src/hawkmoth --cov-report=term --cov-report=html:$(test_dir)/coverage-report
	@echo "Coverage report: file://$(CURDIR)/$(test_dir)/coverage-report/index.html"

CLEAN := $(CLEAN) .coverage $(test_dir)/coverage-report \
	$(shell find $(test_dir) -type d -name __pycache__)
