# -*- makefile -*-
# Copyright (c) 2017-2018, Jani Nikula <jani@nikula.org>
# Licensed under the terms of BSD 2-Clause, see LICENSE for details.

test_dir := test

.PHONY: test
test:
	pytest $(test_dir)
