# SPDX-FileCopyrightText: 2023 Jani Nikula <jani@nikula.org>
# SPDX-License-Identifier: BSD-2-Clause
#
# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - libclang-14-dev
  jobs:
    post_install:
      - python -m pip install --upgrade --no-cache-dir clang==14.0.6

python:
  install:
    - method: pip
      path: .

formats: all

sphinx:
  configuration: doc/conf.py
