# -*- makefile -*-
# SPDX-FileCopyrightText: 2017 Jani Nikula <jani@nikula.org>
# SPDX-License-Identifier: BSD-2-Clause

src_dir := src/hawkmoth

CLEAN := $(CLEAN) $(shell find $(src_dir) -type d -name __pycache__)
