FROM alpine:latest

RUN apk add \
    py3-clang \
    clang-dev \
    musl-dev \
    make

ARG UID=1000
ARG GID=1000
ARG ARCHIVE

WORKDIR /src

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ADD ${ARCHIVE} .

RUN sh venv

ENV PATH=".venv/bin:${PATH}"

USER ${UID}:${GID}
