FROM debian:bookworm

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
	python3-clang \
	python3-venv \
	clang \
	make && \
    apt-get clean

ARG UID=1000
ARG GID=1000
ARG ARCHIVE

# Make it harder for libclang to find headers by coincidence
WORKDIR /path/to/src

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTEST_ADDOPTS "-p no:cacheprovider"

ADD ${ARCHIVE} .

RUN sh venv

ENV PATH=".venv/bin:${PATH}"

USER ${UID}:${GID}
