# SPDX-FileCopyrightText: 2023 Jani Nikula <jani@nikula.org>
# SPDX-License-Identifier: BSD-2-Clause

FROM alpine:latest

RUN apk add \
    py3-clang \
    clang-dev \
    musl-dev \
    make

ARG UID=1000
ARG GID=1000
ARG ARCHIVE
ARG WORKDIR
ARG VENV

WORKDIR ${WORKDIR}

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTEST_ADDOPTS "-p no:cacheprovider"

ADD ${ARCHIVE} .

RUN sh venv ${VENV}

ENV PATH="${VENV}/bin:${PATH}"

USER ${UID}:${GID}
