name: Makefile CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  style:
    name: Check style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install flake8
      - name: Style check
        run: make check

  rst:
    name: Check reStructuredText
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install restructuredtext_lint
      - name: reStructuredText check
        run: make check-rst

  examples:
    name: Check examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install dependencies (apt)
        run: sudo apt-get install -y python3-clang python3-pip
      - name: Examples check
        run: |
          . venv
          make test-examples

  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install dependencies (apt)
        run: sudo apt-get install -y python3-clang python3-pip
      - name: Test
        run: |
          . venv
          make test

  docs:
    name: Check documentation
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies (apt)
        run: sudo apt-get install -y python3-clang python3-pip
      - name: Documentation build check
        run: |
          . venv
          make SPHINXOPTS=-Wn html
