# SPDX-FileCopyrightText: 2023 Jani Nikula <jani@nikula.org>
# SPDX-License-Identifier: BSD-2-Clause

name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  github-release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    steps:
      - name: gh release create
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: gh release create --verify-tag --generate-notes --repo="$GITHUB_REPOSITORY" "$tag"
